export const SAVE_PATIENT_DATA = 'SAVE_PATIENT_DATA';
export const SAVE_PATIENT_TO_LIST = 'SAVE_PATIENT_TO_LIST';
export const GET_DOC_PATIENT_LIST = 'GET_DOC_PATIENT_LIST';
export const SET_SELECTED_PATIENT = 'SET_SELECTED_PATIENT';
export const CLEAR_SELECTED_PATIENT = 'CLEAR_SELECTED_PATIENT';

export const SAVE_NEW_APPOINTMENT = 'SAVE_NEW_APPOINTMENT';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';
export const SET_SELECTED_APPOINTMENT = 'SET_SELECTED_APPOINTMENT';
export const CLEAR_SELECTED_APPOINTMENT = 'CLEAR_SELECTED_APPOINTMENT';
export const LOADING_UNAPPROVED_APPT = 'LOADING_UNAPPROVED';
export const GET_UNAPPROVED_APPT = 'GET_UNAPPROVED_APPT';
export const GET_PATIENTS_APPOINTMENTS = 'GET_PATIENTS_APPOINTMENTS';

export const SET_PATIENT_APPOINTMENTS = 'SET_PATIENT_APPOINTMENTS';

export const SET_PATIENT_FORM_MODE = 'SET_PATIENT_FORM_MODE';

export const GET_VISITS_LIST = 'GET_VISITS_LIST';
export const SET_SELECTED_VISIT = 'SET_SELECTED_VISIT';
export const CLEAR_SELECTED_VISIT = 'CLEAR_SELECTED_VISIT';
export const SET_PATIENT_PAST_VISITS = 'SET_PATIENT_PAST_VISITS';

export const GET_LAB_LIST = 'GET_LAB_LIST';
export const SET_SELECTED_LAB = 'SET_SELECTED_LAB';
export const CLEAR_SELECTED_LAB = 'CLEAR_SELECTED_LAB';
export const SET_PATIENT_LABS = 'SET_PATIENT_LABS';

export const TOGGLE_VIDEO_VIEW = 'TOGGLE_VIDEO_VIEW';

// notification
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const LOADING_NOTIFICATIONS = 'LOADING_NOTIFICATIONS';
