export const GET_PATIENT_APPOINTMENTS = 'GET_PATIENT_APPOINTMENTS';
export const LOADING_PATIENT_APPOINTMENTS = 'LOADING_PATIENT_APPOINTMENTS';
export const GET_PATIENT_PENDING_APPOINTMENTS =
  'GET_PATIENT_PENDING_APPOINTMENTS';
export const LOADING_PENDING_PATIENT_APPOINTMENTS =
  'LOADING_PENDING_PATIENT_APPOINTMENTS';
